name: CI/CD

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y fontconfig libgl1-mesa-dev libglu1-mesa libopencv-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
        pip install ./common_lib/emojilib-1.0.1-cp39-cp39-linux_x86_64.whl
    - name: Run tests
      run: |
        pytest
